name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Check environment before Ruby setup
      run: |
        echo "PATH=$PATH"
        which ruby
        which bundle
        ruby -v || echo "Ruby not installed"
        bundle -v || echo "Bundler not installed"

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.3"
        bundler-cache: true
        working-directory: android

    - name: Check environment after Ruby setup
      run: |
        echo "PATH=$PATH"
        which ruby
        which bundle
        ruby -v
        bundle -v

    - name: Install dependencies
      run: |
        bundle install --verbose
      working-directory: android

    - name: Print Bundler and Ruby environment
      run: |
        ruby -v
        bundle -v
        gem env
        bundle config
      working-directory: android

    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        bundle exec fastlane android upload
      working-directory: android
